#!/bin/bash

# NOTE: this will be run as user vagrant 

# bootstrap dev environment

# Python virtualenv

# create python virtualenv
if [ ! -d "~/env" ]; then
    python3.6 -m venv ~/env
fi

# symlink scripts directory to ~/bin
if [ ! -L "~/bin" ]; then
    ln -fs ~/vagrant/scripts ~/bin
fi

# activate venv
source ~/env/bin/activate
pip install --upgrade pip
pip install wheel

# install webapp developer dependencies
cd ~/emol
pip install -r req-production.txt
pip install -r req-development.txt

mysql -uroot -pqwert -e 'create database emol;'

#export EMOL_CONFIG=/home/vagrant/emol/config/vagrant/config.py
#export FLASK_APP=emol
#cd ~/emol
#pip install -e .
#flask db upgrade