#!/bin/bash

# NOTE: this will be run as user vagrant 

# Make sure the dpkg locks are gone in case we had a previous failure
sudo rm /var/lib/apt/lists/lock
sudo rm /var/cache/apt/archives/lock
sudo rm /var/lib/dpkg/lock


# MySQL with super secret passwords
export DEBIAN_FRONTEND="noninteractive"

sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password qwert"
sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password qwert"

sudo apt-get install -y mysql-server libmysqlclient-dev

# all other packages
sudo apt-get install -y build-essential python3-venv python3-dev ruby ruby-dev libsqlite3-dev supervisor libssl-dev libffi-dev

# set system timezone to match Ealdormere
sudo timedatectl set-timezone America/Toronto

# mailcatcher
[ "$(type -p mailcatcher)" ] || sudo gem install mailcatcher

# cp /etc files
sudo rsync -rltpv /vagrant/files/etc/ /etc

# do the rest from home directory
cd /home/vagrant

# create symlinks to dotfiles
ln -s -f /vagrant/files/dotfiles/.??* .

# restart supervisor to fire up mailcatcher
sudo supervisorctl reload
