#!/bin/bash

# NOTE: this will be run as user vagrant 

# bootstrap dev environment

# Python virtualenv

# create python virtualenv
if [ ! -d "~/env" ]; then
    python3.6 -m venv ~/env
fi

# symlink scripts directory to ~/bin
if [ ! -L "~/bin" ]; then
    ln -s ~/source/scripts ~/bin
fi

# activate venv
source ~/env/bin/activate
pip install wheel

# install webapp developer dependencies
cd ~/source/emol
pip install -r req-development.txt

# prepare the keyfile directory for eMoL setup
if [ ! -d "/home/vagrant/.key" ]; then
    mkdir -p /home/vagrant/.key
    chmod 0700 /home/vagrant/.key
fi

export EMOL_CONFIG=/home/vagrant/source/config/vagrant/config.py
python ~/source/emol/bootstrap-db.py -f