"""empty message

Revision ID: 4c9ce07d4e1d
Revises: 
Create Date: 2019-02-27 20:48:52.144735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9ce07d4e1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combatant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=255), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sca_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=32767), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('_reminders_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('system_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combatant_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('card_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['combatant_id'], ['combatant.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combatant_id', 'discipline_id')
    )
    op.create_table('marshal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('short_title', sa.String(length=255), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('sca_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['officer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy_acceptance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combatant_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('accepted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['combatant_id'], ['combatant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('combatant_id', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('consumed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['combatant_id'], ['combatant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('waiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waiver_date', sa.Date(), nullable=True),
    sa.Column('combatant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['combatant_id'], ['combatant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('is_expiry', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combatant_authorization',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorization.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'authorization_id'),
    sa.UniqueConstraint('card_id', 'authorization_id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiver_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('waiver_id', sa.Integer(), nullable=True),
    sa.Column('is_expiry', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['waiver_id'], ['waiver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warrant',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('marshal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['marshal_id'], ['marshal.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'marshal_id'),
    sa.UniqueConstraint('card_id', 'marshal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warrant')
    op.drop_table('waiver_reminder')
    op.drop_table('user_role')
    op.drop_table('combatant_authorization')
    op.drop_table('card_reminder')
    op.drop_table('waiver')
    op.drop_table('update_request')
    op.drop_table('role')
    op.drop_table('privacy_acceptance')
    op.drop_table('officer')
    op.drop_table('marshal')
    op.drop_table('card')
    op.drop_table('authorization')
    op.drop_table('user')
    op.drop_table('discipline')
    op.drop_table('config')
    op.drop_table('combatant')
    # ### end Alembic commands ###
