# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "emol-staging"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "emol_staging"
    vb.gui = false
  end


  # Override the default ssh port
  config.vm.network :forwarded_port, host: 9022, guest: 22, id: "ssh"

  # mailcatcher
  config.vm.network :forwarded_port, host: 9025, guest: 1080

  # flask development server
  config.vm.network :forwarded_port, host: 9080, guest: 5000
end
